spring.application.name=demoBibliotecaDigital

# 1. Configuracion del Driver y URL de Conexion
spring.datasource.url=jdbc:postgresql://localhost:5432/BibliotecaDigitalBD

# 2. Credenciales de la Base de Datos
spring.datasource.username=postgres
spring.datasource.password=0000

# 3. Configuracion del Pool de Conexiones
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# 4. Configuracion de JPA/Hibernate (ORM)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 5. Generacion Automatica de Tablas
spring.jpa.hibernate.ddl-auto=update

# 6. Mostrar el SQL generado
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 7. Manejo de rutas no encontradas
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false