spring.application.name=demoBiblioteca Digital

# 1. Configuración del Driver y URL de Conexión
spring.datasource.url=jdbc:postgresql://localhost:5432/BibliotecaDigitalBD

# 2. Credenciales de la Base de Datos
spring.datasource.username=postgres
spring.datasource.password=0000

# 3. Configuración del Pool de Conexiones
# Usamos HikariCP, el pool por defecto de Spring Boot, muy eficiente.
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# 4. Configuración de JPA/Hibernate (ORM)
# Esto le dice a Hibernate cómo interactuar con PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 5. Generación Automática de Tablas (IMPORTANTE para empezar)
# Reemplaza 'update' con 'none' cuando el proyecto esté terminado.
spring.jpa.hibernate.ddl-auto=update

# 6. Mostrar el SQL generado (Útil para depuración)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
